// Generated by scripts/export-abis.mjs from contracts/out/HoodPupOfferEscrow.sol/HoodPupOfferEscrow.json
// Do not edit by hand. Run `pnpm abis` after changing the contract.

export const HoodPupOfferEscrowAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "collectionRegistry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ownershipOracle_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hoodPups_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeRouter_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "payoutVault_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rootOwnershipRegistry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "minimumOfferDuration_",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maximumOfferDuration_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "fallback",
    "stateMutability": "payable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "BTC_SETTLEMENT_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_RESERVATION_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PAUSER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "activeBtcOfferForRoot",
    "inputs": [
      {
        "name": "rootKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "approvePaidBtc",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "attestation",
        "type": "tuple",
        "internalType": "struct PuppetTypes.OwnershipAttestation",
        "components": [
          {
            "name": "purpose",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rootTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rootIndex",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "offerTermsHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "currentOutpointHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ownerScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bip322ProofHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payoutMode",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "evmPayout",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "btcPayoutScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "sellerSats",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "grossWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellerWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bitcoinBlockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bitcoinHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "authorizationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "attestorEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "signatures",
        "type": "bytes[]",
        "internalType": "bytes[]"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "btcSettlementCoordinator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buyerNonce",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "clearBtcReservation",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "collectionRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPuppetCollectionRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "computeTermsHash",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "kind",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "rootKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "buyer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "grossWei",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sellerWei",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sellerSats",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createPaidBtcOffer",
    "inputs": [
      {
        "name": "root",
        "type": "tuple",
        "internalType": "struct PuppetTypes.RootId",
        "components": [
          {
            "name": "inscriptionTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "inscriptionIndex",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sellerSats",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "createPaidEvmOffer",
    "inputs": [
      {
        "name": "root",
        "type": "tuple",
        "internalType": "struct PuppetTypes.RootId",
        "components": [
          {
            "name": "inscriptionTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "inscriptionIndex",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "createSelfCastOffer",
    "inputs": [
      {
        "name": "root",
        "type": "tuple",
        "internalType": "struct PuppetTypes.RootId",
        "components": [
          {
            "name": "inscriptionTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "inscriptionIndex",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IFeeRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "finalizeBtcSettlement",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "solver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "paymentDigest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getOffer",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PuppetTypes.Offer",
        "components": [
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "rootKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rootTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rootIndex",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "grossWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellerWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "treasuryWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "protocolWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellerSats",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "termsHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ownershipDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "btcPayoutScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reservedSolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reservationExpiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hoodPups",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IHoodPups"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lockedEscrowWei",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markBtcReserved",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "solver",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reservationExpiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "maximumOfferDuration",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minimumOfferDuration",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nextOfferId",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownershipOracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBitcoinOwnershipOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pauseSettlement",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "payoutVault",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPayoutVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "refundExpired",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "refundUnfillable",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rootOwnershipRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRootOwnershipRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "settlePaidEvm",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "attestation",
        "type": "tuple",
        "internalType": "struct PuppetTypes.OwnershipAttestation",
        "components": [
          {
            "name": "purpose",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rootTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rootIndex",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "offerTermsHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "currentOutpointHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ownerScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bip322ProofHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payoutMode",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "evmPayout",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "btcPayoutScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "sellerSats",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "grossWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellerWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bitcoinBlockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bitcoinHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "authorizationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "attestorEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "signatures",
        "type": "bytes[]",
        "internalType": "bytes[]"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleSelfCast",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "attestation",
        "type": "tuple",
        "internalType": "struct PuppetTypes.OwnershipAttestation",
        "components": [
          {
            "name": "purpose",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "rootTxid",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rootIndex",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "contextId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "offerTermsHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "currentOutpointHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "ownerScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bip322ProofHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "buyer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payoutMode",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "evmPayout",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "btcPayoutScriptHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "sellerSats",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "grossWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sellerWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bitcoinBlockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "bitcoinHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "authorizationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "attestorEpoch",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "signatures",
        "type": "bytes[]",
        "internalType": "bytes[]"
      },
      {
        "name": "collectionProof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unpauseSettlement",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "BtcOfferApproved",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "ownershipDigest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "btcPayoutScriptHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "sellerSats",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BtcReservationCleared",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "solver",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BtcReserved",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "solver",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "reservationExpiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BtcSettlementFinalized",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "solver",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "paymentDigest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowInitialized",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "collectionRegistry",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "ownershipOracle",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "hoodPups",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "feeRouter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "payoutVault",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "rootOwnershipRegistry",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "minimumOfferDuration",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "maximumOfferDuration",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OfferCreated",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "rootKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "grossWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "sellerWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "sellerSats",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "termsHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OfferRefunded",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "unfillable",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OfferSettled",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "rootKey",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "paidTo",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "grossWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipApproved",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "ownershipDigest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "purpose",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "evmPayout",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessControlBadConfirmation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "neededRole",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AttestationFieldMismatch",
    "inputs": [
      {
        "name": "field",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "BtcOfferRequiresSats",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BtcSettlementCoordinatorImmutable",
    "inputs": [
      {
        "name": "active",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "requested",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DirectDepositRejected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DurationBoundsInvalid",
    "inputs": [
      {
        "name": "minimum",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maximum",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExpiry",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minAllowed",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "maxAllowed",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidOfferStatus",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actual",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "expected",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotReservedSolver",
    "inputs": [
      {
        "name": "provided",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "active",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OfferExpired",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "OfferNotExpired",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "PaidOfferRequiresValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReservationLapsed",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "reservationExpiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReservationWindowInvalid",
    "inputs": [
      {
        "name": "requested",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "earliestAllowed",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "latestAllowed",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "RootAlreadyMinted",
    "inputs": [
      {
        "name": "rootKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RootMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "provided",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RootNotMinted",
    "inputs": [
      {
        "name": "rootKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "RootReservationActive",
    "inputs": [
      {
        "name": "rootKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "activeOfferId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SelfCastMustBeZeroValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SelfCastRecipientMismatch",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnexpectedOfferKind",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actual",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "expected",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnexpectedPurpose",
    "inputs": [
      {
        "name": "provided",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "expected",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownOffer",
    "inputs": [
      {
        "name": "offerId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroRootTxid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroValue",
    "inputs": []
  }
] as const;
