#!/usr/bin/env node
/**
 * Export the protocol ABIs from Foundry's build output into `packages/generated-abis`.
 *
 * Run after `forge build`. The output is committed so the SDK, services and frontend all compile
 * against the same ABIs, and so a PR that changes a contract's external surface shows that change
 * in the diff rather than hiding it behind a build step.
 *
 *   node scripts/export-abis.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'contracts', 'out');
const DEST = join(ROOT, 'packages', 'generated-abis', 'src');

/** Only the protocol surface. Mocks, tests and library internals stay out of the SDK. */
const CONTRACTS = [
  'PuppetCollectionRegistry',
  'BitcoinAttestorRegistry',
  'BitcoinOwnershipOracle',
  'PayoutVault',
  'RootOwnershipRegistry',
  'FeeRouter',
  'HoodPups',
  'HoodPupOfferEscrow',
  'BtcSolverSettlement',
  'TourEngine',
];

mkdirSync(DEST, { recursive: true });

const exported = [];
const missing = [];

for (const name of CONTRACTS) {
  const artifactPath = join(OUT_DIR, `${name}.sol`, `${name}.json`);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  } catch {
    missing.push(name);
    continue;
  }

  const banner =
    `// Generated by scripts/export-abis.mjs from contracts/out/${name}.sol/${name}.json\n` +
    '// Do not edit by hand. Run `pnpm abis` after changing the contract.\n\n';

  writeFileSync(
    join(DEST, `${name}.ts`),
    `${banner}export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exported.push(name);
}

writeFileSync(
  join(DEST, 'index.ts'),
  '// Generated by scripts/export-abis.mjs. Do not edit by hand.\n\n' +
    exported.map((n) => `export { ${n}Abi } from './${n}.js';`).join('\n') +
    '\n',
);

console.log(`Exported ${exported.length} ABIs to packages/generated-abis/src`);
if (missing.length > 0) {
  // Not fatal during the build-out, but loud: a silently missing ABI would show up much later as
  // an inscrutable type error in the frontend.
  console.warn(`Missing artifacts (run 'forge build' first?): ${missing.join(', ')}`);
  process.exitCode = missing.length === CONTRACTS.length ? 1 : 0;
}
