#!/usr/bin/env bash
#
# Build a SINGLE-FILE audit bundle: every protocol contract, plus its dependencies, in one
# compilation unit — then zip it.
#
# This complements ./scripts/export-audit-package.sh rather than replacing it. That script gives an
# auditor ten separate per-contract bundles, which is what you want when reviewers split the work by
# contract. This one gives a single file, which is what you want when someone needs to read the
# whole system in one pass, run a whole-program tool over it, or diff two releases of the protocol
# as one artifact.
#
# The naive way to produce "one file" is to concatenate the ten flattened files. That yields ~43k
# lines, roughly 30k of which are the same OpenZeppelin sources pasted ten times, and it does not
# compile — every shared dependency is a duplicate declaration. Instead this generates a single
# aggregate entry point that imports all ten contracts and flattens THAT, so solc's own import
# resolution does the deduplication. The result is ~12.7k lines and is a valid compilation unit.
#
# The bundle is REJECTED unless it compiles standalone in a scratch project with no remappings and
# no lib/ directory. An audit artifact that does not build wastes a reviewer's day.
#
#   ./scripts/export-single-file.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="$ROOT/contracts"
OUT="$ROOT/audit/single-file"
DIST="$ROOT/dist/audit"

export PATH="/root/.foundry/bin:$PATH"

SOLC_VERSION="0.8.28"
EVM_VERSION="shanghai"
OPTIMIZER_RUNS="800"

BUNDLE_NAME="HoodPupsProtocol.flat.sol"

# Deployment-dependency order, not alphabetical: a reader meets each contract after the things it
# depends on. The header's table of contents reuses this same order.
CONTRACT_NAMES=(
  PuppetCollectionRegistry
  BitcoinAttestorRegistry
  BitcoinOwnershipOracle
  PayoutVault
  RootOwnershipRegistry
  FeeRouter
  HoodPups
  HoodPupOfferEscrow
  BtcSolverSettlement
  TourEngine
)

# The aggregate entry point has to live inside src/ for relative imports to resolve, so it exists
# only for the duration of the flatten and is removed on any exit path — including failure. A file
# left behind here would be picked up by the next `forge build`, `forge test`, and CI run.
AGG_DIR="$CONTRACTS/src/__single_file_export"
cleanup() { rm -rf "$AGG_DIR"; }
trap cleanup EXIT

echo "==> Generating the aggregate entry point (temporary)"
mkdir -p "$AGG_DIR"
{
  echo "// SPDX-License-Identifier: MIT"
  echo "pragma solidity 0.8.28;"
  echo
  echo "// Generated by scripts/export-single-file.sh. Never committed — it exists only long enough"
  echo "// for forge to flatten it, and is removed on every exit path including failure."
  for NAME in "${CONTRACT_NAMES[@]}"; do
    echo "import {$NAME} from \"../$NAME.sol\";"
  done
} > "$AGG_DIR/AllContracts.sol"

echo "==> Flattening all ${#CONTRACT_NAMES[@]} contracts into one compilation unit"
RAW="$(mktemp)"
forge flatten "$AGG_DIR/AllContracts.sol" --root "$CONTRACTS" --output "$RAW" >/dev/null 2>&1
cleanup
trap - EXIT

echo "    $(grep -cve '^\s*$' "$RAW") non-blank lines, $(grep -cE '^(abstract )?(contract|library|interface) ' "$RAW") declarations"

echo "==> Proving it compiles standalone — no remappings, no lib/"
SCRATCH="$(mktemp -d)"
mkdir -p "$SCRATCH/src"
cp "$RAW" "$SCRATCH/src/$BUNDLE_NAME"
cat > "$SCRATCH/foundry.toml" <<TOML
[profile.default]
src = "src"
out = "out"
libs = []
solc = "$SOLC_VERSION"
evm_version = "$EVM_VERSION"
optimizer = true
optimizer_runs = $OPTIMIZER_RUNS
TOML
if ! (cd "$SCRATCH" && forge build --silent 2>/dev/null); then
  echo "!!  single-file bundle does NOT compile standalone — refusing to emit it" >&2
  (cd "$SCRATCH" && forge build 2>&1 | tail -30) >&2
  rm -rf "$SCRATCH" "$RAW"
  exit 1
fi
# Every one of the ten must be present as a compiled artifact, not merely as text in the file.
for NAME in "${CONTRACT_NAMES[@]}"; do
  [ -f "$SCRATCH/out/$BUNDLE_NAME/$NAME.json" ] \
    || { echo "!!  $NAME compiled from the bundle but produced no artifact" >&2; rm -rf "$SCRATCH" "$RAW"; exit 1; }
done
echo "    verified — all ${#CONTRACT_NAMES[@]} contracts compile from the bundle alone"

mkdir -p "$OUT" "$DIST"

# The combined ABI is taken from the SCRATCH build, i.e. from the bundle itself rather than from the
# workspace build. If flattening ever altered an interface, this is where it would show up.
echo "==> Collecting ABIs from the bundle build"
python3 - "$SCRATCH/out/$BUNDLE_NAME" "$OUT/abis.json" "${CONTRACT_NAMES[@]}" <<'PYEOF'
import json, sys, pathlib
art_dir, out_path, names = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3:]
abis = {n: json.loads((art_dir / f"{n}.json").read_text())["abi"] for n in names}
pathlib.Path(out_path).write_text(json.dumps(abis, indent=2) + "\n")
print(f"    {len(abis)} ABIs, {sum(len(a) for a in abis.values())} total entries")
PYEOF
rm -rf "$SCRATCH"

COMMIT="$(git -C "$ROOT" rev-parse HEAD)"
DIRTY=0
if ! git -C "$ROOT" diff --quiet HEAD -- contracts/src; then
  DIRTY=1
  echo "!!  working tree is dirty under contracts/src — the bundle will be stamped as such" >&2
fi

echo "==> Writing the bundle header and manifest"
python3 "$ROOT/scripts/lib/single_file_header.py" \
  "$RAW" "$OUT/$BUNDLE_NAME" "$OUT/MANIFEST.json" "$COMMIT" "$DIRTY"
rm -f "$RAW"

# Re-verify AFTER the header is prepended. The header is a comment block, but "it's only comments"
# is exactly the assumption that ships a broken artifact — a stray duplicate license identifier in
# a comment is a hard solc error.
echo "==> Re-verifying the headed bundle compiles"
SCRATCH2="$(mktemp -d)"
mkdir -p "$SCRATCH2/src"
cp "$OUT/$BUNDLE_NAME" "$SCRATCH2/src/"
cat > "$SCRATCH2/foundry.toml" <<TOML
[profile.default]
src = "src"
out = "out"
libs = []
solc = "$SOLC_VERSION"
evm_version = "$EVM_VERSION"
optimizer = true
optimizer_runs = $OPTIMIZER_RUNS
TOML
if ! (cd "$SCRATCH2" && forge build --silent 2>/dev/null); then
  echo "!!  the headed bundle does NOT compile — the header broke it" >&2
  (cd "$SCRATCH2" && forge build 2>&1 | tail -30) >&2
  rm -rf "$SCRATCH2"
  exit 1
fi
rm -rf "$SCRATCH2"
echo "    verified"

echo "==> Writing README"
python3 "$ROOT/scripts/lib/single_file_readme.py" "$OUT" "$BUNDLE_NAME" "$COMMIT"

echo "==> Zipping"
ZIP="$DIST/hoodpups-protocol-single-file-${COMMIT:0:12}.zip"
rm -f "$ZIP"
python3 - "$OUT" "$ZIP" <<'PYEOF'
import pathlib, sys, zipfile
src, zip_path = pathlib.Path(sys.argv[1]), sys.argv[2]
# Deterministic: sorted entries and a fixed timestamp, so the same commit always yields a
# byte-identical archive an auditor can hash and compare.
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for f in sorted(src.iterdir()):
        if f.is_file():
            info = zipfile.ZipInfo(f"hoodpups-protocol/{f.name}", date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, f.read_bytes())
            print(f"    {f.name:<28} {f.stat().st_size:>9,} bytes")
PYEOF

ZIP_SHA="$(sha256sum "$ZIP" | cut -d' ' -f1)"
echo
echo "==> $ZIP"
echo "    $(du -h "$ZIP" | cut -f1)  sha256 $ZIP_SHA"
